### PR TITLE
Image processing Demo Application

### PR DESCRIPTION
**Pull request by adiv2**
Image processing Apex application to convert, compress and resize images.

### CODE REVIEW

**Comment by sanjaypujare** [comment]
Was looking for a readme file to understand the example. Shouldn't there be one? Or some code comments would be helpful.

**Comment by bhupeshchawda** [comment]
+1. Please have a README.md file at the top level - /examples/README.md which outlines in short what the example app does. 
Also have one inside your example application which details how to run your example and what is expected.

**Comment by PramodSSImmaneni** [comment]
Can we get this accross the finish line?

**Comment by bhupeshchawda** [comment]
@PramodSSImmaneni I'll take it up.

**Comment by bhupeshchawda** [comment]
Opened a rebased and cleaned PR #83 
Closing this one.

**Pull request closed without merging**
